/*
-- Query: SELECT * FROM travelbookDB.Posts
LIMIT 0, 50

-- Date: 2020-12-15 19:51
*/
INSERT INTO `Posts` (`id`,`title`,`country`,`city`,`lodging`,`ratings`,`activities`,`body`,`imgTitle`,`imageURL`,`createdAt`,`updatedAt`,`TravelerId`) VALUES (1,'Downtown Tokyo','Japan','Tokyo','Big Hotel',8,'Walking Downtown and Eating Sushi','Decipherment vanquish the impossible bits of moving fluff dispassionate extraterrestrial observer trillion the carbon in our apple pies? Courage of our questions concept of the number one muse about citizens of distant epochs star stuff harvesting star light a very small stage in a vast cosmic arena. Made in the interiors of collapsing stars ship of the imagination the ash of stellar alchemy stirred by starlight made in the interiors of collapsing stars Sea of Tranquility and billions upon billions upon billions upon billions upon billions upon billions upon billions.','Tokyo City Lights','/assets/file_uploads/2020-03-24-tokyo-thumbnail-01.jpg','2020-12-15 17:05:54','2020-12-15 17:05:54',1);
INSERT INTO `Posts` (`id`,`title`,`country`,`city`,`lodging`,`ratings`,`activities`,`body`,`imgTitle`,`imageURL`,`createdAt`,`updatedAt`,`TravelerId`) VALUES (2,'Party in the USA','USA','New York City','The Plaza',7,'eating pretzels','Shores of the cosmic ocean ship of the imagination a mote of dust suspended in a sunbeam Euclid galaxies another world. Inconspicuous motes of rock and gas a still more glorious dawn awaits the sky calls to us laws of physics tingling of the spine as a patch of light. Citizens of distant epochs tendrils of gossamer clouds emerged into consciousness invent the universe with pretty stories for which there\'s little good evidence dream of the mind\'s eye and billions upon billions upon billions upon billions upon billions upon billions upon billions.','New York City','/assets/file_uploads/TimesSquare.jpg','2020-12-15 17:52:41','2020-12-15 17:52:41',1);
INSERT INTO `Posts` (`id`,`title`,`country`,`city`,`lodging`,`ratings`,`activities`,`body`,`imgTitle`,`imageURL`,`createdAt`,`updatedAt`,`TravelerId`) VALUES (3,'Mountain Climbing in Kenya','Kenya','Nairobi','Tents',10,'Camping and Climbing','Give attitude hopped up on goofballs behind the couch run in circles. Give attitude all of a sudden go crazy. Nap all day leave dead animals as gifts, so hunt anything that moves, so intently sniff hand. Behind the couch. Burrow under covers find something else more interesting and rub face on everything. Find something else more interesting intrigued by the shower. Give attitude behind the couch. Throwup on your pillow inspect anything brought into the house so intently sniff hand yet attack feet yet missing until dinner time. Swat at dog.','Camping','/assets/file_uploads/mtkenya.jpg','2020-12-15 18:40:53','2020-12-15 18:40:53',4);
INSERT INTO `Posts` (`id`,`title`,`country`,`city`,`lodging`,`ratings`,`activities`,`body`,`imgTitle`,`imageURL`,`createdAt`,`updatedAt`,`TravelerId`) VALUES (6,'Oooh Chanselisee','France','Paris','A Park Bench',8,'Seeing the Eiffel Tower','La chaux chimique est produite par extraction sélective de CaCO3 chimiquement pur dans les mines et carrières. Tout au long du procédé de fabrication, Graymont surveille attentivement le procédé de façon à produire une chaux calcique vive qui est fortement réactive et surface particulaire élevée. La chaux chimique fournit un rendement exceptionnel pour la neutralisation de l\'acidité, la désulfuration des gaz de combustion, la stabilisation des boues et d\'autres applications industrielles alcalines. La combinaison unique d\'une grande disponibilité du CaO, d\'une réactivité élevée et d\'une surface particulaire élevée signifie qu\'une moins grande quantité de chaux de Graymont est nécessaire pour « faire le travail » comparativement à d\'autres produits de chaux commercialisés.','Arc d Triumph','/assets/file_uploads/paris.jpg','2020-12-15 22:35:34','2020-12-15 22:35:34',30);
INSERT INTO `Posts` (`id`,`title`,`country`,`city`,`lodging`,`ratings`,`activities`,`body`,`imgTitle`,`imageURL`,`createdAt`,`updatedAt`,`TravelerId`) VALUES (7,'BBBBRRRRAZIIIILLLL YO','Brazil','Sao Paulo','Favella',1,'Rap Battles','Lorem ipsizzle dolizzle brizzle amizzle, consectetuer adipiscing ass. Nullam fizzle velizzle, funky fresh bizzle, fizzle quizzle, gravida vizzle, arcu. Pellentesque egizzle tortizzle. Sed erizzle. Mofo izzle bizzle fo shizzle turpis tempizzle i saw beyonces tizzles and my pizzle went crizzle. Mauris pellentesque nibh check it out turpizzle. I saw beyonces tizzles and my pizzle went crizzle doggy tortizzle. Pellentesque fo shizzle rhoncizzle gizzle. In i\'m in the shizzle habitasse platea dictumst. You son of a bizzle dapibus. Curabitur tellus urna, dope doggy, mattizzle fizzle, eleifend vitae, nunc. Crunk suscipizzle. Integer semper velit sizzle purizzle.','Saooo Paulooo','/assets/file_uploads/sao.jpg','2020-12-15 23:02:00','2020-12-15 23:02:00',19);
INSERT INTO `Posts` (`id`,`title`,`country`,`city`,`lodging`,`ratings`,`activities`,`body`,`imgTitle`,`imageURL`,`createdAt`,`updatedAt`,`TravelerId`) VALUES (10,'Ahoooy Maaatey','Carribean','Island','The Beach',11,'Fishing and Drinking','Scuttle draft scurvy hang the jib Gold Road scuppers swab lee scourge of the seven seas chase. Walk the plank list Nelsons folly schooner cog scourge of the seven seas cackle fruit gibbet jolly boat yawl. Log brig bilge water crow\'s nest hardtack reef pirate boatswain maroon grapple.\r\n\r\nMutiny cutlass smartly provost trysail flogging square-rigged knave Sail ho gibbet. Yo-ho-ho keel mutiny furl sheet smartly marooned cog me lateen sail. Log spike yo-ho-ho sloop strike colors rigging fire ship crow\'s nest deadlights Sink me.','Yee Old Clear Blue Water','/assets/file_uploads/ocean.jpg','2020-12-15 23:46:00','2020-12-15 23:46:00',13);
INSERT INTO `Posts` (`id`,`title`,`country`,`city`,`lodging`,`ratings`,`activities`,`body`,`imgTitle`,`imageURL`,`createdAt`,`updatedAt`,`TravelerId`) VALUES (12,'Once Upon a Time in Mexico','Mexico','San Luis Potosi','Abuelitas House',10,'Hiking and Tacos','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed tempor y vitalidad, de modo que el trabajo y el dolor, algunas cosas importantes que hacer eiusmod. A lo largo de los años, vendré, quien no sacará alícuotas de ella la ventaja del ejercicio, de modo que los esfuerzos de estímulo si el distrito escolar y la longevidad. Querer ser un dolor en el cupidatat cillum ha sido criticado en el Duis et dolore magna huir no produce ningún placer resultante. Excepteur cupidatat Los negros no son excepteur, es reconfortante para el alma, es decir, abandonaron los deberes generales de los que tienen la culpa de tus problemas.','SLP at Night','assets/file_uploads/slp.jpg','2020-12-16 01:42:11','2020-12-16 01:42:11',31);
