/*
-- Query: SELECT * FROM travelbookDB.Posts
LIMIT 0, 50

-- Date: 2020-12-15 16:12
*/
INSERT INTO `Posts` (`id`,`title`,`country`,`city`,`lodging`,`ratings`,`activities`,`body`,`imgTitle`,`imageURL`,`createdAt`,`updatedAt`,`TravelerId`) VALUES (1,'Downtown Tokyo','Japan','Tokyo','Big Hotel',8,'Walking Downtown and Eating Sushi','Decipherment vanquish the impossible bits of moving fluff dispassionate extraterrestrial observer trillion the carbon in our apple pies? Courage of our questions concept of the number one muse about citizens of distant epochs star stuff harvesting star light a very small stage in a vast cosmic arena. Made in the interiors of collapsing stars ship of the imagination the ash of stellar alchemy stirred by starlight made in the interiors of collapsing stars Sea of Tranquility and billions upon billions upon billions upon billions upon billions upon billions upon billions.','Tokyo City Lights','/assets/file_uploads/2020-03-24-tokyo-thumbnail-01.jpg','2020-12-15 17:05:54','2020-12-15 17:05:54',1);
INSERT INTO `Posts` (`id`,`title`,`country`,`city`,`lodging`,`ratings`,`activities`,`body`,`imgTitle`,`imageURL`,`createdAt`,`updatedAt`,`TravelerId`) VALUES (2,'Party in the USA','USA','New York City','The Plaza',7,'eating pretzels','Shores of the cosmic ocean ship of the imagination a mote of dust suspended in a sunbeam Euclid galaxies another world. Inconspicuous motes of rock and gas a still more glorious dawn awaits the sky calls to us laws of physics tingling of the spine as a patch of light. Citizens of distant epochs tendrils of gossamer clouds emerged into consciousness invent the universe with pretty stories for which there\'s little good evidence dream of the mind\'s eye and billions upon billions upon billions upon billions upon billions upon billions upon billions.','New York City','/assets/file_uploads/TimesSquare.jpg','2020-12-15 17:52:41','2020-12-15 17:52:41',1);
INSERT INTO `Posts` (`id`,`title`,`country`,`city`,`lodging`,`ratings`,`activities`,`body`,`imgTitle`,`imageURL`,`createdAt`,`updatedAt`,`TravelerId`) VALUES (3,'Mountain Climbing in Kenya','Kenya','Nairobi','Tents',10,'Camping and Climbing','Give attitude hopped up on goofballs behind the couch run in circles. Give attitude all of a sudden go crazy. Nap all day leave dead animals as gifts, so hunt anything that moves, so intently sniff hand. Behind the couch. Burrow under covers find something else more interesting and rub face on everything. Find something else more interesting intrigued by the shower. Give attitude behind the couch. Throwup on your pillow inspect anything brought into the house so intently sniff hand yet attack feet yet missing until dinner time. Swat at dog.','Camping','/assets/file_uploads/mtkenya.jpg','2020-12-15 18:40:53','2020-12-15 18:40:53',4);
